// Libre Audio Suite
// Copyright (C) 2026 Filipe Coelho <falktx@falktx.com>
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#include "DistrhoUtils.hpp"

#ifdef _WIN32
#define RESTRICT __restrict
#else
#define RESTRICT __restrict__
#endif

// --------------------------------------------------------------------------------------------------------------------
// dummy declarations just to get code to compile

namespace {

class Meta {
public:
    void declare(...) {}
};

class UI {
public:
    void addButton(...) {}
    void addCheckButton(...) {}
    void addHorizontalBargraph(...) {}
    void addHorizontalSlider(...) {}
    void addNumEntry(...) {}
    void addVerticalBargraph(...) {}
    void addVerticalSlider(...) {}
    void closeBox(...) {}
    void declare(...) {}
    void openHorizontalBox(...) {}
    void openVerticalBox(...) {}
};

using FaustUI = UI;

}

// --------------------------------------------------------------------------------------------------------------------
// faust DSP interface as generated by faustdr

struct FaustDSP
{
    virtual ~FaustDSP() = default;
    [[nodiscard]] virtual FaustDSP* clone() = 0;
    [[nodiscard]] virtual float latency() const = 0;
    [[nodiscard]] virtual float get(uint32_t index) const = 0;
    [[nodiscard]] virtual int getNumInputs() = 0;
    [[nodiscard]] virtual int getNumOutputs() = 0;
    [[nodiscard]] virtual int getSampleRate() = 0;
    virtual void buildUserInterface(FaustUI* ui_interface) = 0;
    virtual void compute(int count, const float* const* RESTRICT inputs, float** RESTRICT outputs) = 0;
    virtual void init(int sample_rate) = 0;
    virtual void instanceClear() = 0;
    virtual void instanceConstants(int sample_rate) = 0;
    virtual void instanceInit(int sample_rate) = 0;
    virtual void instanceResetUserInterface() = 0;
    virtual void set(uint32_t index, float value) = 0;
};

// --------------------------------------------------------------------------------------------------------------------

START_NAMESPACE_DISTRHO

FaustDSP* createDSP();

END_NAMESPACE_DISTRHO

// --------------------------------------------------------------------------------------------------------------------

#undef RESTRICT
