// Libre Audio Suite
// Copyright (C) 2026 Filipe Coelho <falktx@falktx.com>
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#include "DistrhoUtils.hpp"

#include <vector>

// --------------------------------------------------------------------------------------------------------------------
// parameter metadata for C++ to be generated by faustdr

struct FaustParameterEnumerationValue {
    const char* label;
    int value;
};

struct FaustParameterRequirement {
    const char* context;
    const char* symbol;
    int value;
};

struct FaustParameter
{
    const char* bracket;
    const char* label;
    const char* name;
    const char* symbol;
    const char* tooltip;
    const char* unit;
    float init;
    float min;
    float max;
    float step;
    const FaustParameterEnumerationValue* scalePoints;
    uint scalePointCount;
    FaustParameterRequirement requirement;
    bool isBoolean : 1;
    bool isEasy : 1;
    bool isEnumerator : 1;
    bool isDynamic : 1;
    bool isInteger : 1;
    bool isLogarithmic : 1;
    bool isOutput : 1;
    bool isTrigger : 1;
};

constexpr bool isFaustParameterOutputOrTrigger(const FaustParameter& param)
{
    return param.isOutput || param.isTrigger;
}

// --------------------------------------------------------------------------------------------------------------------

START_NAMESPACE_DISTRHO

const std::vector<FaustParameter>& getFaustParameters();

END_NAMESPACE_DISTRHO

// --------------------------------------------------------------------------------------------------------------------
